version: 2
jobs:
  build:
    docker:
      - image: eldesh/coq:8.6pl1
      - image: eldesh/coq:8.9.0
    steps:
      - checkout
      - run: |
          source ~/.profile
          ./configure.sh
          make
          make -j html
      - persist_to_workspace:
          root: html
          paths: .
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@example.com"
            git config user.name "ci-build"
      - run: ls -la
      - add_ssh_keys:
          fingerprints:
            - "ba:fd:e0:1b:d6:86:54:b9:99:ef:da:02:25:6a:cd:4f"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --message "[skip ci] doc upload" --dist .

workflows:
  version: 2
  build:
    jobs:
      - build
      - docs-deploy:
          requires:
            - build
          filters:
            branches:
              only: master
